#! /usr/bin/env python
# Rafael Fernández López, 2009

def configure(conf):
    conf.sub_config('builtinprotocolhandlers')

def build(bld):
    bld.add_subdirs('builtinprotocolhandlers')
    bld.add_subdirs('defaultstyle')
