#!/usr/bin/env bash

# This file is part of the Ideal Library
# Copyright (C) 2010 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

doxygen --version &> /dev/null

if [ $? -ne 0 ]; then
	echo "!!! Doxygen not installed. Please install it in order to generate documentation"
	exit 1
fi

rm -rf doc &> /dev/null
doxygen .doxygen-config &> /dev/null

if [ $? -eq 0 ]; then
	echo "*** Documentation has been correctly generated under 'doc' directory"
	exit 0
fi

echo "!!! Documentation could not be generated due to an error"
exit 2
