#!/bin/bash

# This file is part of the Ideal Library
# Copyright (C) 2009 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

if [ $# -ne 2 ]; then
    echo "usage: ./generateSkeleton [projectName] [projectPath]"
    exit 1
fi

mkdir $2/$1 &> /dev/null

cp waf $2/$1 &> /dev/null

echo -e "#!/usr/bin/env python

VERSION    = '0.1'
APPNAME    = '$1'
srcdir     = '.'
blddir     = 'build'

def init():
    pass

def set_options(opt):
    opt.tool_options('compiler_cxx')

def configure(conf):
    conf.check_tool('compiler_cxx')
    conf.find_program('pkg-config')
    conf.check_cfg(package = 'idealcore', args = '--cflags --libs')
    conf.env['CXXFLAGS'] += ['-std=c++0x']

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cprogram',
        source       = bld.glob('*.cpp'),
        target       = '$1',
        uselib       = 'IDEALCORE',
        rpath        = bld.env['LIBPATH_IDEALCORE']
    )" >> $2/$1/wscript

echo -e "#include <core/application.h>

int main(int argc, char **argv)
{
    IdealCore::Application app(argc, argv);

    // Here your code :)

    return app.exec();
}" >> $2/$1/main.cpp

echo "*** Skeleton correctly generated at $2/$1"

exit 0
