#! /usr/bin/env python
# Rafael Fernández López, 2009

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cshlib',
        source       = bld.glob('*.cpp'),
        target       = 'defaultstyle',
        includes     = '../..',
        uselib_local = ['idealcore',
                        'idealgui'],
        install_path = '${PREFIX}/lib/ideal/modules'
    )
