#! /usr/bin/env python
#
# This file is part of the Ideal libraries
# Copyright (C) 2009 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.
#

def configure(conf):
    conf.sub_config(['ownModulesTest',
                     'pathTest'])

def build(bld):
    bld.add_subdirs(['basicApp',
                     'callAfterTest',
                     'connectionTest',
                     'crossedDeletions',
                     'deleteAfterSignal',
                     'fileTest',
                     'fileTest2',
                     'fileTest3',
                     'guiTest',
                     'guiTest2',
                     'idleTest',
                     'leakTest',
                     'mkdirTest',
                     'multiSlotTest',
                     'nonBlockingGUI',
                     'ownModulesTest',
                     'pathTest',
                     'processTest',
                     'protocolHandlerTest',
                     'reparentTest',
                     'sigpipeTest',
                     'sigsegvTest',
                     'stringTest',
                     'threadTest',
                     'threadTest2',
                     'threadTest3',
                     'threadTest4',
                     'threadTest5',
                     'threadTest6',
                     'threadTest7',
                     'threadTest8',
                     'threadTest9',
                     'threadTest10',
                     'timerTest',
                     'timerTest2',
                     'virtualTest'])
