#! /usr/bin/env python
# Rafael Fernández López, 2009

def configure(conf):
    pass

def build(bld):
    bld.add_subdirs(['basicApp',
                     'callAfterTest',
                     'connectionTest',
                     'crossedDeletions',
                     'deleteAfterSignal',
                     'extensionLoaderTest',
                     'fileTest',
                     'guiTest',
                     'guiTest2',
                     'idleTest',
                     'leakTest',
                     'multiSlotTest',
                     'pathTest',
                     'processTest',
                     'protocolHandlerTest',
                     'reparentTest',
                     'sigpipeTest',
                     'sigsegvTest',
                     'stringTest',
                     'threadTest',
                     'threadTest2',
                     'threadTest3',
                     'threadTest4',
                     'threadTest5',
                     'threadTest6',
                     'threadTest7',
                     'timerTest',
                     'timerTest2'])
