#! /usr/bin/env python
# Rafael Fernández López, 2009

VERSION    = '1.0'
APPNAME    = 'test'
srcdir     = '.'
blddir     = 'build'

def init():
    pass

def set_options(opt):
    opt.tool_options('compiler_cxx')

def configure(conf):
    conf.check_tool('compiler_cxx')
    conf.find_program('pkg-config')
    conf.check_cfg(package = 'idealcore', args = '--cflags --libs')
    conf.env['CXXFLAGS'] += ['-std=c++0x']

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cprogram',
        source       = 'main.cpp',
        target       = 'mediaPlayer',
        uselib       = 'IDEALCORE',
        rpath        = bld.env['LIBPATH_IDEALCORE']
    )

