#! /usr/bin/env python
#
# This file is part of the Ideal libraries
# Copyright (C) 2009 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.
#

def configure(conf):
    conf.check_cfg(package = 'cairo-xlib-xrender', args = '--cflags --libs')
    if not conf.env['HAVE_CAIRO_XLIB_XRENDER'] == 1:
        conf.fatal('Cannot continue without cairo. Please, install the development package and try again')

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cshlib',
        source       = bld.glob('*.cpp') +
                       bld.glob('private/xorg/*.cpp'),
        target       = 'idealgui',
        includes     = ['..',
                        '../core'],
        uselib       = 'CAIRO-XLIB-XRENDER',
        uselib_local = 'idealcore',
        vnum         = bld.env['LIBVERSION']
    )
    bld.new_task_gen('subst',
        source = 'idealgui.pc.in',
        target = 'idealgui.pc',
        dict   = {'PREFIX' : bld.env['PREFIX'], 'LIBS' : '-lidealgui', 'VERSION' : bld.env['LIBVERSION']}
    )
    bld.install_files('${PREFIX}/lib/pkgconfig', 'idealgui.pc')
    bld.install_files('${PREFIX}/include/ideal/gui', '*.h')
    bld.install_files('${PREFIX}/include/ideal/gui/interfaces', 'interfaces/*.h')
