#! /usr/bin/env python
# Rafael Fernández López, 2009

def configure(conf):
    conf.check_cfg(package = 'cairo-xlib-xrender', args = '--cflags --libs')
    if not conf.env['HAVE_CAIRO_XLIB_XRENDER'] == 1:
        conf.fatal('Cannot continue without cairo. Please, install the development package and try again')

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cshlib',
        source       = bld.glob('*.cpp') +
                       bld.glob('private/xorg/*.cpp'),
        target       = 'idealgui',
        includes     = ['..',
                        '../core'],
        uselib       = 'CAIRO-XLIB-XRENDER',
        uselib_local = 'idealcore',
        vnum         = bld.env['LIBVERSION']
    )
    bld.new_task_gen('subst',
        source = 'idealgui.pc.in',
        target = 'idealgui.pc',
        dict   = {'PREFIX' : bld.env['PREFIX'], 'LIBS' : '-lidealgui', 'VERSION' : bld.env['LIBVERSION']}
    )
    bld.install_files('${PREFIX}/lib/pkgconfig', 'idealgui.pc')
    bld.install_files('${PREFIX}/include/ideal/gui', '*.h')
