#! /usr/bin/env python
# Rafael Fernández López, 2009

import Options

def configure(conf):
    if not Options.options.release:
        conf.sub_config('tests')
    conf.env['LIB_CORE'] = ['rt', 'dl', 'pthread']
    conf.check_cfg(package = 'liburiparser', args = '--cflags --libs')
    if not conf.env['HAVE_LIBURIPARSER'] == 1:
        conf.fatal('Cannot continue without liburiparser. Please, install the development package and try again')
    conf.check_tool('misc')

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cshlib',
        source       = bld.glob('*.cpp') +
                       bld.glob('interfaces/*.cpp') +
                       bld.glob('private/*.cpp') +
                       bld.glob('private/posix/*.cpp'),
        target       = 'idealcore',
        includes     = '..',
        uselib       = ['CORE',
                        'LIBURIPARSER'],
        vnum         = bld.env['LIBVERSION']
    )
    bld.new_task_gen('subst',
        source = 'idealcore.pc.in',
        target = 'idealcore.pc',
        dict   = {'PREFIX' : bld.env['PREFIX'],
                  'LIBS' : '-lidealcore',
                  'VERSION' : bld.env['LIBVERSION']}
    )
    if not bld.env['RELEASE']:
        bld.add_subdirs('tests')
    bld.install_files('${PREFIX}/lib/pkgconfig', 'idealcore.pc')
    bld.install_files('${PREFIX}/include/ideal/core', '*.h')
    bld.install_files('${PREFIX}/include/ideal/core/interfaces', 'interfaces/*.h')

