#! /usr/bin/env python
# Rafael Fernández López, 2009

def configure(conf):
    conf.define('OWNMODULESTEST_PREFIX', conf.env['PREFIX'])
    conf.write_config_header('ownmodulestest_conf.h')

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cprogram',
        source       = 'main.cpp',
        target       = 'ownModulesTest',
        includes     = ['.',
                        '../..'],
        uselib       = 'IDEAL',
        uselib_local = 'idealcore',
        install_path = None
    )
    bld.new_task_gen(
        features     = 'cxx cshlib',
        source       = 'module.cpp',
        target       = 'ownModulesTestModule',
        includes     = '../..',
        uselib       = 'IDEAL',
        uselib_local = 'idealcore',
        install_path = '${PREFIX}/lib/ownModulesTest/modules'
    )
