#! /usr/bin/env python
# Rafael Fernández López, 2009

def configure(conf):
    conf.define('PATHTEST_PREFIX', conf.env['PREFIX'])
    conf.write_config_header('pathtest_conf.h')

def build(bld):
    bld.new_task_gen(
        features     = 'cxx cprogram',
        source       = 'main.cpp',
        target       = 'pathTest',
        includes     = ['.',
                        '../..'],
        uselib       = 'IDEAL',
        uselib_local = 'idealcore',
        install_path = None
    )
